// The project's words as a Vale style (ORC-029 pass 4d, decision 6). The dictionary the owner approved into the
// blueprint's draft (the studio's words: this checks the lead's, the PE's and the designer's text) says which words to avoid; this module turns it into Vale substitution rules, so the prose check reports
// "Use '<term>', not '<word>'." as an error. The style is generated into the service's data folder, never into the
// repository: <dataDir>/vale/<projectId>/ holds a copy of the repository's STE80 style, the generated Project style and
// a configuration that uses both. Without a dictionary in force (or with no avoided words), nothing is generated and
// the check uses the repository's configuration as before.

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { dictionaryInDraft } from "../../src/domain/studio/blueprint";
import type { DictionaryEntry } from "../../src/domain/studio/types";
import type { State } from "../../src/domain/types";
import { VALE_CONFIG } from "./vale";

/** The generated style's name: its rules are "Project.Term1", "Project.Term2"… */
export const PROJECT_STYLE = "Project";
/** The repository's style, copied beside the generated one (Vale reads styles from one folder). */
const BASE_STYLE = "STE80";

const escape = (w: string) => w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
/** A string for YAML: JSON's double-quoted form is valid YAML. */
const q = (x: string) => JSON.stringify(x);
const either = (words: string[]) => (words.length < 2 ? words.map((w) => `'${w}'`).join("") : `${words.slice(0, -1).map((w) => `'${w}'`).join(", ")} or '${words.at(-1)}'`);

/**
 * One substitution rule per term that avoids words: each avoided word (without case, whole words only) is an error
 * whose message names the term to use, and whose description, which the prose record keeps, names them all. A term
 * that contains an avoided word ("trip plan" when "plan" is avoided) is an exception, so the term itself is never
 * reported.
 */
export function wordRules(entries: DictionaryEntry[]): { name: string; yaml: string }[] {
  return entries.flatMap((e, i) => {
    if (!e.avoid.length) return [];
    const inside = entries.map((x) => x.term).filter((t) => e.avoid.some((w) => new RegExp(`\\b${escape(w)}\\b`, "i").test(t)));
    const yaml = [
      `# Generated from the project's dictionary: the term "${e.term.replace(/"/g, "'")}". Do not edit.`,
      "extends: substitution",
      `message: ${q("Use '%s', not '%s'. The project's dictionary says so.")}`,
      `description: ${q(`Use '${e.term}', not ${either(e.avoid)} (the project's dictionary).`)}`,
      "level: error",
      "ignorecase: true",
      ...(inside.length ? ["exceptions:", ...inside.map((t) => `  - ${q(`(?i)${escape(t)}`)}`)] : []),
      "swap:",
      ...e.avoid.map((w) => `  ${q(escape(w))}: ${q(e.term)}`),
      "",
    ].join("\n");
    return [{ name: `Term${i + 1}`, yaml }];
  });
}

/** The generated configuration: the repository's, with the project's style added to the styles Markdown is checked with. */
function configText(): string {
  const base = readFileSync(VALE_CONFIG, "utf8");
  const based = /^BasedOnStyles\s*=\s*(.+)$/m;
  if (!based.test(base)) throw new Error(`${VALE_CONFIG} names no BasedOnStyles.`);
  return `# Generated by Orchestrator from the repository's configuration and the project's dictionary in force (server/prose/words.ts). Do not edit.\n${base.replace(based, (_, styles: string) => `BasedOnStyles = ${styles.trim()}, ${PROJECT_STYLE}`)}`;
}

/** Write a file only when its text differs, so a check that changes nothing writes nothing. */
function put(path: string, text: string) {
  let now: string | undefined;
  try {
    now = readFileSync(path, "utf8");
  } catch {
    now = undefined;
  }
  if (now === text) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

/**
 * The Vale configuration that checks with the project's words: written into `<dataDir>/vale/<projectId>/` from the
 * draft's dictionary, and its path returned. Undefined when the draft has no dictionary or it avoids no word: then the
 * repository's configuration applies. Rules of terms no longer in the dictionary are removed.
 */
export function projectValeConfig(dataDir: string, state: State): string | undefined {
  const words = dictionaryInDraft(state);
  const rules = words ? wordRules(words.entries) : [];
  const id = state.project.id;
  if (!/^[A-Za-z0-9._-]+$/.test(id) || id === "." || id === "..") throw new Error(`"${id}" cannot name a folder.`);
  const root = join(dataDir, "vale", id);
  if (!rules.length) return undefined;
  const styles = join(root, "styles");
  const repoStyle = join(dirname(VALE_CONFIG), "styles", BASE_STYLE);
  const base = Object.fromEntries(readdirSync(repoStyle).filter((x) => x.endsWith(".yml")).map((f) => [f, readFileSync(join(repoStyle, f), "utf8")]));
  const project = Object.fromEntries(rules.map((r) => [`${r.name}.yml`, r.yaml]));
  for (const [style, files] of [[BASE_STYLE, base], [PROJECT_STYLE, project]] as const) {
    const folder = join(styles, style);
    // A rule no longer in the style (a term dropped from the dictionary) goes.
    try {
      for (const f of readdirSync(folder)) if (!(f in files)) rmSync(join(folder, f), { force: true });
    } catch {
      /* not written yet */
    }
    for (const [f, text] of Object.entries(files)) put(join(folder, f), text);
  }
  const config = join(root, ".vale.ini");
  put(config, configText());
  return config;
}
