// Markdown export of a task and import of tasks from Markdown.

import { effectiveDefault, flowRef } from "../flows";
import { instantiate, toDef } from "../pipeline";
import { type SpecContent, type State, ControlError } from "../types";
import { currentSpec, currentVision, draft, event } from "./core";
import { stateLabel } from "./presentation";

/** Board as Markdown, for repository visibility. The service's database remains the source of truth. */
export function exportMarkdown(s: State): string {
  const rows = [...s.tasks]
    .sort((a, b) => a.priority - b.priority || a.id.localeCompare(b.id))
    .map((t) => {
      const c = currentSpec(t).content;
      const sel = c.options.find((o) => o.id === c.selectedOptionId);
      const cell = (x: string) => x.replace(/\|/g, "\\|").replace(/\n/g, " ");
      return `| ${t.id} | ${cell(c.title)} | ${stateLabel(s, t)} | P${t.priority} | ${cell(sel ? `${sel.id}: ${sel.name}` : "—")} | ${t.integration?.status ?? "—"} | ${t.specs[0].author} |`;
    });
  const v = currentVision(s);
  return `# ${s.project.name}

Generated by Orchestrator on ${new Date().toISOString()}. Exported for visibility; edit tasks in Orchestrator.

## Vision (r${v.rev})

${v.text}

Current focus: ${v.focus}

## Tasks

| ID | Title | State | Priority | Selected approach | Integration | Author |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n")}
`;
}

/**
 * Import a Markdown task table once, preserving IDs. Recognises a header row containing "ID" and a
 * title-like column ("Title", "Task", "Outcome"), and optionally "State"/"Status". Rows whose state
 * reads done become done tasks with "legacy spec unavailable"; all others become held proposals that
 * cannot run until a spec is written. Existing IDs are skipped.
 */
export function importMarkdown(state: State, markdown: string, now: string): { state: State; imported: string[]; skipped: string[] } {
  const lines = markdown.split(/\r?\n/).filter((l) => l.trim().startsWith("|"));
  const split = (l: string) => l.trim().replace(/^\|/, "").replace(/\|$/, "").split(/(?<!\\)\|/).map((c) => c.trim().replace(/\\\|/g, "|"));
  const s = draft(state);
  const imported: string[] = [];
  const skipped: string[] = [];
  let header: string[] | null = null;
  for (const line of lines) {
    const cells = split(line);
    if (cells.every((c) => /^:?-{3,}:?$/.test(c))) continue;
    const lower = cells.map((c) => c.toLowerCase());
    if (lower.includes("id") && lower.some((c) => ["title", "task", "outcome", "proposed outcome"].includes(c))) {
      header = lower;
      continue;
    }
    if (!header) continue;
    const col = (...names: string[]) => header!.findIndex((h) => names.includes(h));
    const linkText = (c: string | undefined) => (c ?? "").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
    const id = linkText(cells[col("id")]).replace(/[^A-Za-z0-9._-]/g, "");
    const title = linkText(cells[col("title", "task", "outcome", "proposed outcome")]);
    const prioCell = Number.parseInt(linkText(cells[col("priority")]), 10);
    const stateCell = (cells[col("state", "status")] ?? "").toLowerCase();
    if (!id || !title) continue;
    // IDs become part of git branch names and must not collide with the lead's reserved id.
    if (!/^[A-Za-z0-9][A-Za-z0-9_-]*(\.[A-Za-z0-9_-]+)*$/.test(id) || id.endsWith(".lock") || id.toUpperCase() === "LEAD" || id.length > 40) {
      skipped.push(`${id} (invalid id)`);
      continue;
    }
    if (s.tasks.some((t) => t.id === id)) {
      skipped.push(id);
      continue;
    }
    const done = /\b(done|complete|completed|shipped)\b/.test(stateCell);
    const content: SpecContent = {
      title: title.slice(0, 200),
      area: "Imported",
      whyNow: "",
      outcome: title,
      benefit: "",
      successCriteria: [],
      scopeIncluded: [],
      scopeExcluded: [],
      options: [{ id: "A", name: "Legacy", approach: "Imported from a Markdown board; no specification was recorded.", benefit: "", effort: "", risks: "", reversibility: "" }],
      recommendedOptionId: "A",
      selectedOptionId: "A",
      decidedBy: "user",
      rationale: "Legacy spec unavailable.",
      uncertainty: "",
      overrideReason: "",
      acceptance: [],
      validationPlan: "",
      rollback: "",
      effort: "small",
    };
    // Imported tasks run the project default flow.
    const flow = effectiveDefault(s);
    const defs = structuredClone(flow.steps).map(toDef);
    const ref = flowRef(flow, "default");
    s.tasks.push({
      id,
      priority: Number.isFinite(prioCell) && prioCell > 0 ? Math.min(99, prioCell) : 5,
      lifecycle: done ? "done" : "proposed",
      hold: false,
      holdBeforeStart: !done,
      specs: [{ rev: 1, at: now, author: "user", reason: "Imported from Markdown", content }],
      steps: instantiate(defs).map((st) => (done ? { ...st, state: "done" as const } : st)),
      roleOverrides: {},
      dependsOn: [],
      createdAt: now,
      updatedAt: now,
      decisionAt: now,
      pipelineRev: 1,
      pipelineHistory: [{ rev: 1, at: now, author: "user", reason: `Imported; created from the ${flow.name} flow`, steps: defs, flow: ref }],
      flow: ref,
      flowSince: 1,
      legacySpecUnavailable: true,
      ...(done ? { integration: { status: "not-needed" as const } } : {}),
    });
    imported.push(id);
  }
  if (!imported.length && !skipped.length) throw new ControlError("No task table found. Expected a Markdown table with an ID column and a Title (or Task/Outcome) column.");
  event(s, now, "user", "spec", `Imported ${imported.length} task${imported.length === 1 ? "" : "s"} from Markdown${skipped.length ? `; skipped existing ${skipped.join(", ")}` : ""}. Open imported tasks need a spec before they run.`);
  return { state: s, imported, skipped };
}
